### ISSUE TITLE
Android "Complete action using" on link click

### ISSUE THREAD

**Issue by mmotamimi** [BranchMetrics/cordova-ionic-phonegap-branch-deep-linking-attribution#481]
Hi, 
when i click on the link on android, and i have the app installed, it gives me the popup of "Complete action using" and under it i have the app and chrome.
is there a way to force the link to open the app if it exists without giving me options of apps to use?

![image](https://user-images.githubusercontent.com/8076587/42756219-d7c697da-8903-11e8-80c3-0ff39f66fa27.png)

**Comment by sequoiaat** [comment]
Please refer
https://docs.branch.io/pages/deep-linking/android-app-links/

First Enable App Link on Branch dashboard settings and enter SHA256 finger print of your app.
In order for Android to auto verify your app link association your app need an entry is Google's DLA(Digital asset linking file). Branch is doing that for you when you provide your SHA256 finger print for keystone.
Please go to settings -> link in Branch dashboard and make sure you check Enable App Link option and enter debug / live key store SHA256 finger print.
