### ISSUE TITLE
Updating from 3.1.5 to 3.1.6 resulted to a multidex error when building

### ISSUE THREAD

**Issue by rj-david** [BranchMetrics/cordova-ionic-phonegap-branch-deep-linking-attribution#554]
```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForDebug'.
> java.lang.RuntimeException: java.lang.RuntimeException: com.android.builder.dexing.DexArchiveMergerException: Unable to merge dex
```

Enabling multidex in our project resulted to more errors. Before I try to deal with multidex, trying to figure out if someone knew how to fix the above issue.

No problem with version 3.1.5

**Comment by Tallyb** [comment]
I believe the issue arises from this line: 
https://github.com/BranchMetrics/cordova-ionic-phonegap-branch-deep-linking/blob/7df49cb0ee351a6faa6eddf052464167baedf4a8/src/android/dependencies/rules.gradle#L2
so if other *.aar files exist in the project, they will be re-copied and cause duplications.

**Comment by ghaiat** [comment]
Hello. any update on this ? it s quite a big issue ....

**Comment by penguin20000** [comment]
We're getting the same issue, downgrading to 3.1.5 fixed the problem

**Comment by echo-branch** [comment]
Thanks for bringing this to our attention.  We have a ticket to dig into this issue next sprint.

One quick thing to check, is the old branch jar file and the aar file both present?   If that's the case we missed the removal of the old jar file.

**Comment by csalmi-branch** [comment]
@rj-david , can you give us a bit more information about your configuration? What version of Cordova are you using, gradle version, android sdk version, etc.? 

We are investigating this issue, but with all of the different interdependencies, its hard to know exactly what will fix the problem in this scenario. A fix for Cordova 7 is different than a fix for Cordova 9.

**Comment by adrianyg7** [comment]
I can replicate the error message in case both .jar and .aar files are both present in lib folder. But upgrading from 3.1.5 to 3.1.6 won’t produce both files into the same folder.

Upgrading will successfully remove old .jar file and then create the new .aar file.

This might be related to https://github.com/BranchMetrics/cordova-ionic-phonegap-branch-deep-linking-attribution/issues/558 and perhaps already fixed, unless anyone still having this issue provides the installed software + repro steps, this is most likely being closed.

**Comment by echo-branch** [comment]
This should be resolved in the latest release.
