### ISSUE TITLE
Plugin fails to install on Cordova 9.x

### ISSUE THREAD

**Issue by bytenik** [BranchMetrics/cordova-ionic-phonegap-branch-deep-linking-attribution#561]
On Cordova 9.x, the following error occurs during the installation of branch-cordova-sdk:

```
Failed to install 'branch-cordova-sdk': CordovaError: Using "requireCordovaModule" to load non-cordova module "q" is not supported. Instead, add this module to your dependencies and use regular "require" to load it.
    at Context.requireCordovaModule (C:\Users\bytenik\Documents\Projects\BallStreet\app\node_modules\cordova-lib\src\hoo
ks\Context.js:57:15)
    at Object.install (C:\Users\bytenik\Documents\Projects\BallStreet\app\plugins\branch-cordova-sdk\src\scripts\npm\dow
nloadNpmDependencies.js:18:23)
    at run (C:\Users\bytenik\Documents\Projects\BallStreet\app\plugins\branch-cordova-sdk\src\scripts\hooks\beforePlugin
Install.js:11:22)
    at runScriptViaModuleLoader (C:\Users\bytenik\Documents\Projects\BallStreet\app\node_modules\cordova-lib\src\hooks\H
ooksRunner.js:181:32)
    at runScript (C:\Users\bytenik\Documents\Projects\BallStreet\app\node_modules\cordova-lib\src\hooks\HooksRunner.js:1
57:16)
    at C:\Users\bytenik\Documents\Projects\BallStreet\app\node_modules\cordova-lib\src\hooks\HooksRunner.js:125:20
    at processTicksAndRejections (internal/process/next_tick.js:81:5)
Failed to restore plugin "branch-cordova-sdk" from config.xml. You might need to try adding it again. Error: Using "requireCordovaModule" to load non-cordova module "q" is not supported. Instead, add this module to your dependencies and use regular "require" to load it.
```

**Comment by aaronneon2** [comment]
Facing same issue here with cordova 9.0.0. This plugin works fine in cordova 8.1.1.  I am now trying cordova 8.1.2.

**Comment by rj-david** [comment]
`requireCordovaModule()` has been deprecated
https://github.com/apache/cordova-lib/pull/707

**Comment by anrip** [comment]
Deprecate requireCordovaModule for non-Cordova modules

**Comment by abomadi** [comment]
any help to get this fixed ?

**Comment by Juanperezc** [comment]
Same issue

**Comment by paulstelzer** [comment]
I enlarged my fork `innomobile-branch-cordova-sdk@3.1.8-beta.2` that removes requireCordovaModule and changed it with normal require. My fork is also using CocoaPods (see #533).

Anyone who wants to test it, take a look at https://www.npmjs.com/package/innomobile-branch-cordova-sdk . The steps:

1. `cordova plugin add innomobile-branch-cordova-sdk`

2. Replace the line with `branch-cordova-sdk` inside config.xml with `<plugin name="innomobile-branch-cordova-sdk" spec="^3.1.8-beta.2" />`

I am using it on my app and seems working - but if anyone else can check too would be great :)

**Comment by adrianyg7** [comment]
Solved on https://github.com/BranchMetrics/cordova-ionic-phonegap-branch-deep-linking-attribution/pull/563

**Comment by echo-branch** [comment]
This should be resolved in the latest release.
