### ISSUE TITLE
iOS Universal Links - Data is only passed via app.link template

### ISSUE THREAD

**Issue by justjoeyuk** [BranchMetrics/cordova-ionic-phonegap-branch-deep-linking-attribution#576]
If I share a link from the app, and generate a applinks URL, with metadata and such, everything works as expected minus the data attached to the link.

If I open the link from twitter, it opens the template on app.link and shows the “this page wants to open SomeApp”. If I tap yes, the app opens but with no data.

However, if I click “no” and then click “Open App” on the template page, the app opens with all of the data. It’s not just Twitter, if I open it via Facebook or other platform, the app opens but with no data, even though the data is certainly there.

I’ve included the canonicalIdentifier and all the standard fields and my own metadata.

Is there any commonly known reason for this?

First picture is what I see when I open the app via basically anything except the app.link template. Second one is what I see when I open it via app.link.

![494C9B88-8874-4832-B0C8-B741D4F7D2E1](https://user-images.githubusercontent.com/987388/64495679-de6a1e00-d294-11e9-8008-b957835bbf43.png)

![62D056E9-9A48-4C18-B15D-555BF7C5BD77](https://user-images.githubusercontent.com/987388/64495684-f17cee00-d294-11e9-813d-6c8985eedb63.png)

And this is what I see when I click the link from Twitter:

![F98CDF6E-27D6-43F0-B812-1C6845162A5E](https://user-images.githubusercontent.com/987388/64495724-897ad780-d295-11e9-9bcb-7473ec00e3bf.png)

**Comment by justjoeyuk** [comment]
I have discovered what this issue was. If anybody else is looking for a solution - I removed the Facebook4 plugin as it currently swallows all other deeplinking data.

I'm sure somebody over there will have a fork that is compatible with Branch but I am able to just remove it.

**Comment by justjoeyuk** [comment]
Just for further clarification - it looks like this version of the Facebook4 plugin fixes the issue: https://github.com/GexxOn/cordova-plugin-facebook4 - the specific change is here: https://github.com/GexxOn/cordova-plugin-facebook4/commit/3dcfe6cb670f795f6319595f61883f15cae8de02

**Comment by tarun57** [comment]
Hi justjoeyuk,
i'm using ionic 3 but my ionic app is not open from link on ios it will redirect on link but on android its working perfect.
