### ISSUE TITLE
generateShortUrl crash when contentImageUrl link is too long

### ISSUE THREAD

**Issue by bipoza** [BranchMetrics/cordova-ionic-phonegap-branch-deep-linking-attribution#583]
I was using this plugin time ago and work perfectly, but when add content Image Url path too long it crash. I dont know how limit have this parameter length.

`ERROR Error: Uncaught (in promise): Error creating universal url: [object Object]`

**Comment by echo-branch** [comment]
Could we get a sample problem url?

**Comment by bipoza** [comment]
Sorry. It was a momentary problem, possibly caused by calling the service. A few days later the error disappeared and it works correctly.
The issue can be closed
