### ISSUE TITLE
Failed to install on Cocoapods 1.8.*

### ISSUE THREAD

**Issue by safead** [BranchMetrics/cordova-ionic-phonegap-branch-deep-linking-attribution#605]
Can you please update the lib to be compatible with Cocoapods 1.8.*?

It is impossible to install previous Cocoapods 1.7.5 because the lack of the files in their repository, and using the last 1.8.4 version we got this error:

> Failed to install 'branch-cordova-sdk': undefined
> CordovaError: Promise rejected with non-error: 'The CocoaPods repo has not been synced yet, this will take a long time (approximately 500MB as of Sept 2016). Please run `pod setup` first to sync the repo.'
>     at /usr/local/lib/node_modules/cordova/bin/cordova:29:15
>     at processTicksAndRejections (internal/process/task_queues.js:93:5)
> 

Please assist, thanks.

**Comment by Mapiac** [comment]
x2

**Comment by codinronan** [comment]
Hi @safead and @Mapiac are you able to provide more information about this issue?

I have done the following:
>   Using Node 10.15 (but this worked on 12 LTS as well)
>   Verified everything working as expected using CocoaPods 1.6.0 (plugin adds successfully, builds successfully, runs in emulator)
>   Installed CocoaPods 1.8.4
>   Created a version project
>   Add branch-cordova-sdk cordova plugin
>   Built (in Xcode) and run without issue

Can you provide additional information about your build environment?
Cordova version, branch-cordova-sdk version, node version, Xcode version

Finally, make sure your Xcode is fully up to date -- there was a bug in the early iOS 13 Xcode releases related to Podfile.lock management that would have resulted in that error. (As of today, the latest Xcode version is 11.3.1)

**Comment by codinronan** [comment]
Hi guys by the way this was a cordova-ios bug, you can see the details and the fix here:

https://github.com/apache/cordova-ios/pull/719

If you use cordova-ios >= 5.1.0 you'll get the fixed version.

**Comment by echo-branch** [comment]
This should be resolved in the latest release.
