### ISSUE TITLE
Changelog is not up to date

### ISSUE THREAD

**Issue by Luro91** [BranchMetrics/cordova-ionic-phonegap-branch-deep-linking-attribution#621]
I noticed that the changelog is out of sync with the releases:

https://github.com/BranchMetrics/cordova-ionic-phonegap-branch-deep-linking-attribution/blob/master/CHANGELOG.md

https://github.com/BranchMetrics/cordova-ionic-phonegap-branch-deep-linking-attribution/releases

**Comment by bklastaitis-branch** [comment]
should be there now, sorry!
