### ISSUE TITLE
can I not show "safari cannot open the page becuase address is invalid"

### ISSUE THREAD

**Issue by skout90** [BranchMetrics/cordova-ionic-phonegap-branch-deep-linking-attribution#635]
Hello.

When Ios, app is not installed, if I click url(https://moneypin.app.link/test-ios) in ios note apps.

[![IMG-0624.png](https://i.postimg.cc/zBRgQ670/IMG-0624.png)](https://postimg.cc/9RC0Rxv7)

appear this error. and then can move app store.

can i not show this error message? I hope to move directly app store, if app not installed

my config is

**Default Link Domain** : moneypin.app.link
**Link Setting => ios url scheme** : moneypin://

```xml
    <branch-config>
        <uri-scheme value="moneypin" />
        <link-domain value="moneypin.app.link" />
    </branch-config>
```

I already set ios universal link option.

**Comment by echo-branch** [comment]
Please file a support ticket.  It's possible this is a dashboard configuration issue.

**Comment by skout90** [comment]
@echo-branch  Thanks for reply. I will attempt to solve this myself. And then will file a support ticket.

**Comment by skout90** [comment]
This turned out to be due to cache issue.
reference below issue.
https://github.com/BranchMetrics/ios-branch-deep-linking-attribution/tree/master/Branch-TestBed-Swift#test
