### ISSUE TITLE
Removing references to UIwebview to comply with Apple policy

### ISSUE THREAD

**Issue by tryhardest** [BranchMetrics/cordova-ionic-phonegap-branch-deep-linking-attribution#643]
https://cordova.apache.org/howto/2020/03/18/wkwebviewonly.html

As per this blog post, Apple is rejecting any plugin or SDK's with any UIwebview references, which the Branch SDK has. Just want to make aware and see if there a plan to remove references to UIwebview to comply with this Apple policy?

**Comment by echo-branch** [comment]
Have you updated to the latest version?  This was done a while ago.

**Comment by timmliu** [comment]
Could you confirm which version(s) this was released?

**Comment by echo-branch** [comment]
I believe these are the releases.  4.0.0+ mainline.  3.4.0 lts.

https://github.com/BranchMetrics/cordova-ionic-phonegap-branch-deep-linking-attribution/releases/tag/v4.0.0

https://github.com/BranchMetrics/cordova-ionic-phonegap-branch-deep-linking-attribution/releases/tag/v3.4.0
