### ISSUE TITLE
iOS cmd line build fails

### ISSUE THREAD

**Issue by peterpeterparker** [BranchMetrics/cordova-ionic-phonegap-branch-deep-linking-attribution#647]
Hi,

I just added `branch-cordova-sdk@4.1.3` to my mobile application and now face the following error when I build the application through the command line `ionic cordova build ios`.

```

warning: MobileCoreServices has been renamed. Use CoreServices instead. (in target 'Branch' from project 'Pods')
** BUILD FAILED **


The following build commands failed:
	CompileC /Users/daviddalbusco/Library/Developer/Xcode/DerivedData/MyApp-bigzspsapvykkddxevioqzdcuvoi/Build/Intermediates.noindex/MyApp.build/Debug-iphonesimulator/MyApp.build/Objects-normal/x86_64/AppDelegate+BranchSdk.o /Users/daviddalbusco/projects/bonjour/myapp/platforms/ios/MyApp/Plugins/branch-cordova-sdk/AppDelegate+BranchSdk.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
xcodebuild: Command failed with exit code 65
[ERROR] An error occurred while running subprocess cordova.
```

If I build the app in Xcode v11.4, I do not face any errors.

P.S. A duplicate of https://github.com/BranchMetrics/cordova-ionic-phonegap-branch-deep-linking-attribution/issues/642 ?

**Comment by jffs** [comment]
same here

**Comment by adrianyg7** [comment]
Hey @peterpeterparker Can you provide additional information about your build environment?
Cordova version, node/npm versions, cordova-ios version, installed plugins.

**Comment by peterpeterparker** [comment]
It was like more than a year ago, I've got no clue anymore and probably went another way. Therefore I close this issue.
