### ISSUE TITLE
can't get path and query string parameters from deep link in Ionic 3 app

### ISSUE THREAD

**Issue by AleCat83** [BranchMetrics/cordova-ionic-phonegap-branch-deep-linking-attribution#663]
Hello,

I am trying to create a deep linking system using branch.io for my mobile app iOS and ANDROID using Ionic 3. 

I have this URL

https://myurl.com/shop/productId=1234

I created a QuickLink into the dashboard with:

$deeplink_path: /shop
$canonical_url: https://myurl.com

In the Application (Ionic 3 with cordova-branch-sdk) I init the session calling

this.branch.initSession().then(branchIoData => {
 console.log(JSON.stringify(branchIoData))
}

When I click on the URL from iOS or Android I correctly receive the event with the following data

{"+clicked_branch_link":false,"+is_first_session":false} 

but I don't see any way to extract the path and the parameter productId=1234.

How can I accomplish this?

Also, the event seems to be working only if the app is closed, isn't it supposed to work if the app is active?

Thanks

**Comment by sebafra** [comment]
> Hello,
> 
> I am trying to create a deep linking system using branch.io for my mobile app iOS and ANDROID using Ionic 3.
> 
> I have this URL
> 
> https://myurl.com/shop/productId=1234
> 
> I created a QuickLink into the dashboard with:
> 
> $deeplink_path: /shop $canonical_url: https://myurl.com
> 
> In the Application (Ionic 3 with cordova-branch-sdk) I init the session calling
> 
> this.branch.initSession().then(branchIoData => { console.log(JSON.stringify(branchIoData)) }
> 
> When I click on the URL from iOS or Android I correctly receive the event with the following data
> 
> {"+clicked_branch_link":false,"+is_first_session":false}
> 
> but I don't see any way to extract the path and the parameter productId=1234.
> 
> How can I accomplish this?
> 
> Also, the event seems to be working only if the app is closed, isn't it supposed to work if the app is active?
> 
> Thanks

Hi, I have the same problem in iOS. Did you find the solution?

**Comment by nsingh-branch** [comment]
> > Hello,
> > I am trying to create a deep linking system using branch.io for my mobile app iOS and ANDROID using Ionic 3.
> > I have this URL
> > https://myurl.com/shop/productId=1234
> > I created a QuickLink into the dashboard with:
> > $deeplink_path: /shop $canonical_url: https://myurl.com
> > In the Application (Ionic 3 with cordova-branch-sdk) I init the session calling
> > this.branch.initSession().then(branchIoData => { console.log(JSON.stringify(branchIoData)) }
> > When I click on the URL from iOS or Android I correctly receive the event with the following data
> > {"+clicked_branch_link":false,"+is_first_session":false}
> > but I don't see any way to extract the path and the parameter productId=1234.
> > How can I accomplish this?
> > Also, the event seems to be working only if the app is closed, isn't it supposed to work if the app is active?
> > Thanks
> 
> Hi, I have the same problem in iOS. Did you find the solution?

@sebafra Just to clarify, you're opening the app with a Branch link, but not receiving any of the link data?

**Comment by sebafra** [comment]
> > > Hello,
> > > I am trying to create a deep linking system using branch.io for my mobile app iOS and ANDROID using Ionic 3.
> > > I have this URL
> > > https://myurl.com/shop/productId=1234
> > > I created a QuickLink into the dashboard with:
> > > $deeplink_path: /shop $canonical_url: https://myurl.com
> > > In the Application (Ionic 3 with cordova-branch-sdk) I init the session calling
> > > this.branch.initSession().then(branchIoData => { console.log(JSON.stringify(branchIoData)) }
> > > When I click on the URL from iOS or Android I correctly receive the event with the following data
> > > {"+clicked_branch_link":false,"+is_first_session":false}
> > > but I don't see any way to extract the path and the parameter productId=1234.
> > > How can I accomplish this?
> > > Also, the event seems to be working only if the app is closed, isn't it supposed to work if the app is active?
> > > Thanks
> > 
> > 
> > Hi, I have the same problem in iOS. Did you find the solution?
> 
> @sebafra Just to clarify, you're opening the app with a Branch link, but not receiving any of the link data?

Yes @nsingh-branch , The problem was with iOS. I´m using ionic 5 with capacitor. 
I solved editing manually AppDelegate.swift with missing values.
Now it´s working. 
Thanks
