### ISSUE TITLE
Enable support for SKAdNetwork (iOS 14)

### ISSUE THREAD

**Issue by sebaferreras** [BranchMetrics/cordova-ionic-phonegap-branch-deep-linking-attribution#667]
Hello,

Yesterday I received this email related to the latest changes in iOS 14:

> Hi Sebastian,
> 
> As you’ve likely heard by now, iOS 14 (coming in September) will bring significant changes to the mobile industry, including partial deprecation of the IDFA (Identifier For Advertisers). Branch has been hard at work for the last two months, preparing for these changes.
> 
> **Required action**: if you have an iOS app and use Branch for paid ads attribution, you must update your app to enable support for SKAdNetwork (Apple’s new attribution framework).
> 
> - Instructions on how to make this app integration update can be found [here](http://go2.branch.io/s0ae0Bw0CTYX0F07fL10j0T). This is a technical change, and will need to be done by an iOS engineer.
> 
> - Further information on Branch's support for SKAdNetwork can be found [here](http://go2.branch.io/K007fFT00Bcy1jjCL0wY0T0).
> 
> If you do not use Branch for paid ads attribution, there is no required app integration update at this time. However, the IDFA changes may still impact you, depending on your product usage and internal data infrastructure (i.e., if you rely heavily on IDFAs to tie exported Branch events to users in your internal data lake). We encourage you to read more on our [iOS 14 resource hub](http://go2.branch.io/HF001070YLvCfTf0BwT00Hj), reach out to your Branch CSM, or email [support@branch.io](http://go2.branch.io/j7YT0w1BF00fC0LYTjb0e00).

In the [Branch docs](https://help.branch.io/using-branch/docs/branchskadnetwork-integration-instructions#section-app-option-1-use-the-branch-sdk-to-manage-skadnetwork) it's mentioned that support for the **SKAdNetwork** in the Cordova plugin is TBD but I couldn't find any other information about this in this repo.

From what I can see in my tests, the Branch Cordova plugin won't break when using the app on iOS 14 (tested on iOS 14 beta 6), but the IDFA will be _zeroed_ out – i.e. the random numbers and letters will be replaced with zeros. And that, of course, will affect the paid ads attribution reports.

Is there any information about when the plugin will be updated to support SKAdNetwork? Since this will directly affect every Cordova app using Branch for paid ads attribution.

Thanks.

**Comment by echo-branch** [comment]
It's in progress, we hope to have it done this week.

**Comment by Sebschock** [comment]
What is the status on the update for the iOS 14 update?

**Comment by KirstenStake** [comment]
@echo-branch any status on this please?

**Comment by echo-branch** [comment]
@KirstenStake 
Sorry this ticket should have been updated and closed.  The current Cordova includes iOS SDK 0.35.0 which has support for this.

https://github.com/BranchMetrics/ios-branch-deep-linking-attribution/releases
