### ISSUE TITLE
Incompatible block pointer types

### ISSUE THREAD

**Issue by SamuelMichelRiad** [BranchMetrics/cordova-ionic-phonegap-branch-deep-linking-attribution#687]
Hi all,

I'm getting the following error when compiling for iOS:

Incompatible block pointer types sending 'void (^)(BranchLastAttributedTouchData * _Nullable __strong)' to parameter of type 'void (^ _Nonnull)(BranchLastAttributedTouchData * _Nullable __strong, NSError * _Nullable __strong)'

The plugin version is 4.2.3. Any ideas?

<img width="1440" alt="Screen Shot 2021-05-02 at 1 32 20 AM" src="https://user-images.githubusercontent.com/9570587/116795494-6e05b580-aae6-11eb-9e5f-b86ba9835984.png">

**Comment by echo-branch** [comment]
Thanks for the heads up.  Working on a fix.

**Comment by echo-branch** [comment]
This should be fixed in the 4.2.4 patch release.
