### ISSUE TITLE
Android 12 requires app links verification similar to iOS AASA

### ISSUE THREAD

**Issue by rex-iotum** [BranchMetrics/cordova-ionic-phonegap-branch-deep-linking-attribution#697]
Deeplinking on Android 12 no longer works without explicit user input to enable each deep link after app install.

Is there any way for this plugin to generate the correct `<intent-filter>` format as per this guide?
https://developer.android.com/training/app-links/verify-site-associations

    
    <intent-filter android:autoVerify="true">
        <action android:name="android.intent.action.VIEW" />
        <category android:name="android.intent.category.DEFAULT" />
        <category android:name="android.intent.category.BROWSABLE" />

        
        <data android:scheme="http" />
        <data android:scheme="https" />

        
        <data android:host="..." />
    </intent-filter>

![image](https://user-images.githubusercontent.com/64922037/145098038-42878d75-34c9-4ad1-a521-ea6c741e8c4f.png)

**Comment by rex-iotum** [comment]
Ah nevermind, looking at the source code your plugin already does so. We're only missing the AASA style file hosted in `.well_known`

**Comment by jf-branch** [comment]
Hi @rex-iotum. When you properly set up Android App links in the Branch Dashboard Configuration tab with your corresponding SHA256 certs for different build types/environments, we will properly host your DAL(digital asset links) file within the app.link/.well-known

**Comment by rex-iotum** [comment]
@jf-branch Hi, I would suggest making it more prominent that Android 12 now requires using "App Links" instead of the usual Link -> Browser -> App handoff.
