### ISSUE TITLE
Can Branch.io fallback to a different app

### ISSUE THREAD

**Issue by Brandi-Youreka** [BranchMetrics/cordova-ionic-phonegap-branch-deep-linking-attribution#712]
I am currently developing a new app to replace my old mobile app. The old and new mobile app will both exist at the same time to give the customers time to transition from the old to new app. The old mobile app is using branch.io for deep linking and I would like to continue using those deep links for my new mobile app. Is there a way to make the deep link:

1. Open the new mobile app if it is install
2. If the new mobile app is not installed, open the old mobile app
3. If both the new and old mobile app are not installed, direct the user to the new mobile app listing in the store

As you can see, I would like my deep link to try to open the new app and have the old app as a fallback. Is this possible?

**Comment by echo-branch** [comment]
Sounds like you need multiple app IDs associated with the same domain. We do not have a self service page for this. You should file a support ticket to have this added to your app.link domain.
